# @package _global_

model_name: 'PointConT'
dataset: 'Washington'   
dataset_dir: 'data/'
log_dir: 'runs/'
cfg_path: 'wandb/'
wandb_name: 'baseline'
seed: 9344
batch_size: 32  
test_batch_size: 32  
epochs: 250   
num_classes: 50  

